require('dotenv').config({ path: require('path').join(__dirname, '..', '.env') });
const mongoose = require('mongoose');
const Product = require('../models/Product');

const products = [
  // ── CLEANSERS ──────────────────────────────────────────────────────────────
  {
    name: 'Hydrating Facial Cleanser',
    brand: 'CeraVe',
    category: 'cleanser',
    description:
      'A gentle, non-foaming cleanser that hydrates while it cleans. Formulated with hyaluronic acid and three essential ceramides to restore the skin barrier. Suitable for normal to dry skin.',
    ingredients: ['Ceramide NP', 'Ceramide AP', 'Ceramide EOP', 'Hyaluronic Acid', 'Glycerin', 'Niacinamide'],
    skinTypes: ['dry', 'normal', 'sensitive'],
    concerns: ['dryness', 'hydration', 'sensitivity'],
    price: 15.97,
    priceRange: 'budget',
    rating: 4.8,
    reviewCount: 42000,
    imageUrl: 'https://placehold.co/400x400?text=CeraVe+Hydrating+Cleanser',
    buyUrl: 'https://www.amazon.com/dp/B01MSSDEPK',
    isActive: true,
    dermatologistApproved: true,
    tags: ['gentle', 'fragrance-free', 'non-comedogenic'],
  },
  {
    name: 'Foaming Facial Cleanser',
    brand: 'CeraVe',
    category: 'cleanser',
    description:
      'An oil-removing foaming cleanser that leaves skin feeling clean without disrupting the skin barrier. Contains ceramides and niacinamide to control shine. Ideal for oily and combination skin.',
    ingredients: ['Ceramide NP', 'Ceramide AP', 'Ceramide EOP', 'Niacinamide', 'Zinc PCA'],
    skinTypes: ['oily', 'combination'],
    concerns: ['acne', 'oiliness', 'pores'],
    price: 14.97,
    priceRange: 'budget',
    rating: 4.7,
    reviewCount: 38000,
    imageUrl: 'https://placehold.co/400x400?text=CeraVe+Foaming+Cleanser',
    buyUrl: 'https://www.amazon.com/dp/B00TTBY1KI',
    isActive: true,
    dermatologistApproved: true,
    tags: ['foaming', 'oil-control', 'fragrance-free'],
  },
  {
    name: 'Toleriane Hydrating Gentle Cleanser',
    brand: 'La Roche-Posay',
    category: 'cleanser',
    description:
      'A soap-free, fragrance-free cleanser designed for sensitive skin. The prebiotic formula maintains the skin microbiome while gently removing impurities. Leaves skin soft and comfortable.',
    ingredients: ['Glycerin', 'Niacinamide', 'La Roche-Posay Prebiotic Thermal Water', 'Ceramide NP'],
    skinTypes: ['sensitive', 'dry', 'normal'],
    concerns: ['sensitivity', 'redness', 'dryness'],
    price: 17.99,
    priceRange: 'budget',
    rating: 4.8,
    reviewCount: 22000,
    imageUrl: 'https://placehold.co/400x400?text=LRP+Toleriane+Cleanser',
    buyUrl: 'https://www.amazon.com/dp/B01N7T7JKJ',
    isActive: true,
    dermatologistApproved: true,
    tags: ['soap-free', 'microbiome-friendly', 'gentle'],
  },
  {
    name: 'Ultra Facial Cream Cleanser',
    brand: "Kiehl's",
    category: 'cleanser',
    description:
      'A cream-to-foam cleanser that gently removes makeup and impurities while leaving skin nourished. Enriched with squalane and glycerin for a moisturizing cleanse. Perfect for dry and sensitive skin types.',
    ingredients: ['Squalane', 'Glycerin', 'Apricot Kernel Oil', 'Sodium Hyaluronate'],
    skinTypes: ['dry', 'sensitive', 'normal'],
    concerns: ['dryness', 'sensitivity'],
    price: 24.0,
    priceRange: 'budget',
    rating: 4.5,
    reviewCount: 8500,
    imageUrl: 'https://placehold.co/400x400?text=Kiehls+Cleanser',
    buyUrl: 'https://www.kiehls.com',
    isActive: true,
    dermatologistApproved: true,
    tags: ['cream-cleanser', 'nourishing', 'squalane'],
  },
  {
    name: 'Gentle Skin Cleanser',
    brand: 'Cetaphil',
    category: 'cleanser',
    description:
      'A mild, non-irritating cleanser that effectively removes dirt and excess oil without stripping moisture. Suitable for all skin types including sensitive. The dermatologist-recommended formula maintains the skin\'s natural pH.',
    ingredients: ['Water', 'Cetyl Alcohol', 'Propylene Glycol', 'Sodium Lauryl Sulfate', 'Polyoxyl 40 Stearate'],
    skinTypes: ['all'],
    concerns: ['sensitivity', 'dryness', 'redness'],
    price: 12.49,
    priceRange: 'budget',
    rating: 4.6,
    reviewCount: 55000,
    imageUrl: 'https://placehold.co/400x400?text=Cetaphil+Cleanser',
    buyUrl: 'https://www.amazon.com/dp/B079RDNXNQ',
    isActive: true,
    dermatologistApproved: true,
    tags: ['mild', 'non-stripping', 'all-skin-types'],
  },
  {
    name: 'Micellar Cleansing Water',
    brand: 'Garnier',
    category: 'cleanser',
    description:
      'A micellar water that effortlessly removes waterproof makeup, dirt, and oil without rinsing. The gentle formula is alcohol-free and suitable for sensitive skin. Leaves skin clean, fresh, and hydrated.',
    ingredients: ['Aqua', 'Hexylene Glycol', 'Glycerin', 'Disodium EDTA', 'Poloxamer 184'],
    skinTypes: ['all', 'sensitive'],
    concerns: ['sensitivity', 'dryness'],
    price: 8.99,
    priceRange: 'budget',
    rating: 4.6,
    reviewCount: 30000,
    imageUrl: 'https://placehold.co/400x400?text=Garnier+Micellar+Water',
    buyUrl: 'https://www.amazon.com/dp/B01J7LP4EM',
    isActive: true,
    dermatologistApproved: false,
    tags: ['micellar', 'no-rinse', 'makeup-remover'],
  },

  // ── TONERS ────────────────────────────────────────────────────────────────
  {
    name: 'Witch Hazel Toner',
    brand: 'Thayers',
    category: 'toner',
    description:
      'An alcohol-free facial toner with aloe vera that soothes and tightens pores without over-drying. Contains witch hazel extract to control excess oil. A cult favourite for balanced, clear-looking skin.',
    ingredients: ['Witch Hazel', 'Aloe Barbadensis Leaf Juice', 'Glycerin', 'Citric Acid'],
    skinTypes: ['oily', 'combination', 'normal'],
    concerns: ['oiliness', 'pores', 'acne'],
    price: 10.95,
    priceRange: 'budget',
    rating: 4.6,
    reviewCount: 40000,
    imageUrl: 'https://placehold.co/400x400?text=Thayers+Witch+Hazel',
    buyUrl: 'https://www.amazon.com/dp/B000LB7G7W',
    isActive: true,
    dermatologistApproved: false,
    tags: ['alcohol-free', 'pore-minimizing', 'aloe-vera'],
  },
  {
    name: '2% BHA Liquid Exfoliant',
    brand: "Paula's Choice",
    category: 'toner',
    description:
      'A cult-favourite leave-on exfoliant with 2% salicylic acid that unclogs pores and smooths skin texture. The gentle formula exfoliates inside the pore lining and on the surface. Suitable for blemish-prone and blackhead-prone skin.',
    ingredients: ['Salicylic Acid 2%', 'Green Tea Extract', 'Methylpropanediol', 'Sodium Hydroxide'],
    skinTypes: ['oily', 'combination'],
    concerns: ['acne', 'blackheads', 'pores', 'texture'],
    price: 34.0,
    priceRange: 'mid-range',
    rating: 4.8,
    reviewCount: 18000,
    imageUrl: 'https://placehold.co/400x400?text=Paulas+Choice+BHA',
    buyUrl: 'https://www.paulaschoice.com',
    isActive: true,
    dermatologistApproved: true,
    tags: ['BHA', 'exfoliant', 'salicylic-acid'],
  },
  {
    name: 'Pitera Essence',
    brand: 'SK-II',
    category: 'toner',
    description:
      'A legendary essence powered by over 90% Pitera—a bio-ingredient rich in vitamins, amino acids, and minerals. Intensively improves skin texture and radiance over consistent use. A cornerstone of Korean-inspired skincare routines.',
    ingredients: ['Galactomyces Ferment Filtrate (Pitera)', 'Niacinamide', 'Sodium Hyaluronate', 'Butylene Glycol'],
    skinTypes: ['all'],
    concerns: ['aging', 'brightness', 'texture', 'hyperpigmentation'],
    price: 185.0,
    priceRange: 'luxury',
    rating: 4.7,
    reviewCount: 9000,
    imageUrl: 'https://placehold.co/400x400?text=SK-II+Pitera',
    buyUrl: 'https://www.sk-ii.com',
    isActive: true,
    dermatologistApproved: false,
    tags: ['essence', 'luxury', 'brightening', 'ferment'],
  },
  {
    name: 'Glycolic Acid 7% Toning Solution',
    brand: 'The Ordinary',
    category: 'toner',
    description:
      'An exfoliating toning solution with 7% glycolic acid that helps improve skin radiance, clarity, and texture. Amino acids and aloe vera buffer the acid to minimise irritation. Best used in the evening.',
    ingredients: ['Glycolic Acid 7%', 'Aloe Vera', 'Ginseng Root Extract', 'Tasmanian Pepperberry'],
    skinTypes: ['normal', 'oily', 'combination'],
    concerns: ['texture', 'brightness', 'hyperpigmentation', 'acne'],
    price: 9.9,
    priceRange: 'budget',
    rating: 4.5,
    reviewCount: 25000,
    imageUrl: 'https://placehold.co/400x400?text=TO+Glycolic+Toner',
    buyUrl: 'https://theordinary.com',
    isActive: true,
    dermatologistApproved: false,
    tags: ['AHA', 'glycolic-acid', 'exfoliating'],
  },

  // ── SERUMS ────────────────────────────────────────────────────────────────
  {
    name: 'C E Ferulic',
    brand: 'SkinCeuticals',
    category: 'serum',
    description:
      'The gold standard in vitamin C serums combining 15% L-ascorbic acid, vitamin E, and ferulic acid. This patented formula protects against environmental damage and neutralises free radicals. Visibly brightens and firms over time.',
    ingredients: ['L-Ascorbic Acid 15%', 'Alpha Tocopherol 1%', 'Ferulic Acid 0.5%', 'Panthenol', 'Bisabolol'],
    skinTypes: ['normal', 'dry', 'combination'],
    concerns: ['aging', 'brightness', 'hyperpigmentation', 'sun-protection'],
    price: 182.0,
    priceRange: 'luxury',
    rating: 4.7,
    reviewCount: 7500,
    imageUrl: 'https://placehold.co/400x400?text=SkinCeuticals+CE+Ferulic',
    buyUrl: 'https://www.skinceuticals.com',
    isActive: true,
    dermatologistApproved: true,
    tags: ['vitamin-C', 'antioxidant', 'brightening', 'anti-aging'],
  },
  {
    name: 'Hyaluronic Acid 2% + B5',
    brand: 'The Ordinary',
    category: 'serum',
    description:
      'A lightweight serum combining multiple molecular weights of hyaluronic acid for multi-depth hydration. Vitamin B5 (panthenol) supports the skin barrier and enhances moisture retention. Suitable for all skin types including oily.',
    ingredients: ['Sodium Hyaluronate', 'Sodium Hyaluronate Crosspolymer', 'Panthenol', 'Glycerin', 'Ahnfeltia Concinna Extract'],
    skinTypes: ['all'],
    concerns: ['dryness', 'hydration', 'sensitivity'],
    price: 6.8,
    priceRange: 'budget',
    rating: 4.6,
    reviewCount: 50000,
    imageUrl: 'https://placehold.co/400x400?text=TO+HA+Serum',
    buyUrl: 'https://theordinary.com',
    isActive: true,
    dermatologistApproved: false,
    tags: ['hyaluronic-acid', 'hydrating', 'lightweight'],
  },
  {
    name: 'Niacinamide 10% + Zinc 1%',
    brand: 'The Ordinary',
    category: 'serum',
    description:
      'A high-strength vitamin B3 serum that reduces the appearance of blemishes and congestion. The zinc salt of pyrrolidone carboxylic acid supports the skin surface and helps regulate sebum. Non-greasy and fast-absorbing.',
    ingredients: ['Niacinamide 10%', 'Zinc PCA 1%', 'Glycerin', 'Pentylene Glycol', 'Xanthan Gum'],
    skinTypes: ['oily', 'combination', 'normal'],
    concerns: ['acne', 'pores', 'oiliness', 'brightness'],
    price: 5.9,
    priceRange: 'budget',
    rating: 4.5,
    reviewCount: 65000,
    imageUrl: 'https://placehold.co/400x400?text=TO+Niacinamide',
    buyUrl: 'https://theordinary.com',
    isActive: true,
    dermatologistApproved: false,
    tags: ['niacinamide', 'zinc', 'pore-minimizing', 'sebum-control'],
  },
  {
    name: 'Retinol 0.5% in Squalane',
    brand: 'The Ordinary',
    category: 'serum',
    description:
      'A moderate-strength retinol serum suspended in squalane to minimise dryness and irritation. Supports skin cell turnover to reduce the appearance of fine lines and improve texture. Best introduced gradually into an evening routine.',
    ingredients: ['Retinol 0.5%', 'Squalane', 'Ethyl Linoleate', 'BHT'],
    skinTypes: ['normal', 'combination', 'oily'],
    concerns: ['aging', 'fine-lines', 'texture', 'acne'],
    price: 7.9,
    priceRange: 'budget',
    rating: 4.4,
    reviewCount: 20000,
    imageUrl: 'https://placehold.co/400x400?text=TO+Retinol',
    buyUrl: 'https://theordinary.com',
    isActive: true,
    dermatologistApproved: false,
    tags: ['retinol', 'anti-aging', 'squalane'],
  },
  {
    name: 'A-Passioni Retinol Cream',
    brand: 'Drunk Elephant',
    category: 'serum',
    description:
      'A 1% vegan retinol serum in a nutrient-rich formula with wild marula oil and supportive peptides. Dramatically improves the look of fine lines, wrinkles, and uneven skin tone. The cocktail of skin-loving ingredients minimises sensitivity.',
    ingredients: ['Retinol 1%', 'Vitis Vinifera (Grape) Seed Oil', 'Marula Oil', 'Peptides Complex', 'Glycerin'],
    skinTypes: ['normal', 'combination', 'dry'],
    concerns: ['aging', 'fine-lines', 'wrinkles', 'texture'],
    price: 74.0,
    priceRange: 'mid-range',
    rating: 4.5,
    reviewCount: 6000,
    imageUrl: 'https://placehold.co/400x400?text=Drunk+Elephant+Retinol',
    buyUrl: 'https://www.drunkelephant.com',
    isActive: true,
    dermatologistApproved: true,
    tags: ['retinol', 'anti-aging', 'luxury', 'vegan'],
  },
  {
    name: 'Vitamin C Brightening Serum',
    brand: 'TruSkin',
    category: 'serum',
    description:
      'A daily anti-aging serum with vitamin C, hyaluronic acid, and vitamin E that fades dark spots and evens skin tone. The lightweight formula absorbs quickly and layers well under moisturiser. A budget-friendly alternative to prestige vitamin C serums.',
    ingredients: ['Vitamin C (Ascorbic Acid)', 'Hyaluronic Acid', 'Vitamin E', 'Aloe Vera', 'Jojoba Oil'],
    skinTypes: ['all'],
    concerns: ['brightness', 'hyperpigmentation', 'aging', 'dark-circles'],
    price: 19.99,
    priceRange: 'budget',
    rating: 4.3,
    reviewCount: 100000,
    imageUrl: 'https://placehold.co/400x400?text=TruSkin+Vitamin+C',
    buyUrl: 'https://www.amazon.com/dp/B00Y3MBD3Q',
    isActive: true,
    dermatologistApproved: false,
    tags: ['vitamin-C', 'brightening', 'affordable'],
  },
  {
    name: 'Youth to the People Superfood Serum',
    brand: 'Youth to the People',
    category: 'serum',
    description:
      'A nutrient-packed, plant-based serum with spinach, green tea, and kale that protects against environmental stressors. Hyaluronic acid provides an immediate plumping effect. Vegan, fragrance-free, and suitable for all skin types.',
    ingredients: ['Hyaluronic Acid', 'Spinach Extract', 'Kale Extract', 'Green Tea Extract', 'Glycerin', 'Vitamin C'],
    skinTypes: ['all'],
    concerns: ['aging', 'brightness', 'hydration'],
    price: 48.0,
    priceRange: 'mid-range',
    rating: 4.4,
    reviewCount: 5500,
    imageUrl: 'https://placehold.co/400x400?text=YTTP+Superfood+Serum',
    buyUrl: 'https://www.youthtothepeople.com',
    isActive: true,
    dermatologistApproved: false,
    tags: ['vegan', 'antioxidant', 'plant-based'],
  },

  // ── MOISTURIZERS ──────────────────────────────────────────────────────────
  {
    name: 'Moisturizing Cream',
    brand: 'CeraVe',
    category: 'moisturizer',
    description:
      'A rich yet non-greasy moisturising cream with three essential ceramides and hyaluronic acid that provides 24-hour hydration. The MVE delivery technology releases ingredients slowly throughout the day. Suitable for very dry to normal skin.',
    ingredients: ['Ceramide NP', 'Ceramide AP', 'Ceramide EOP', 'Hyaluronic Acid', 'Glycerin', 'Cholesterol', 'Petrolatum'],
    skinTypes: ['dry', 'normal', 'sensitive'],
    concerns: ['dryness', 'hydration', 'eczema', 'sensitivity'],
    price: 19.97,
    priceRange: 'budget',
    rating: 4.9,
    reviewCount: 75000,
    imageUrl: 'https://placehold.co/400x400?text=CeraVe+Moisturizing+Cream',
    buyUrl: 'https://www.amazon.com/dp/B00TTD9BRC',
    isActive: true,
    dermatologistApproved: true,
    tags: ['ceramides', 'fragrance-free', 'rich-moisturizer'],
  },
  {
    name: 'PM Facial Moisturizer',
    brand: 'Olay',
    category: 'moisturizer',
    description:
      'A nighttime moisturiser with niacinamide and peptides that works overnight to regenerate skin and reduce signs of aging. Lightweight gel-cream texture absorbs quickly without feeling heavy. Clinically proven to improve skin tone in 4 weeks.',
    ingredients: ['Niacinamide', 'Pentapeptide-4', 'Glycerin', 'Dimethicone', 'Sodium Hyaluronate'],
    skinTypes: ['normal', 'combination', 'oily'],
    concerns: ['aging', 'brightness', 'texture', 'fine-lines'],
    price: 28.99,
    priceRange: 'mid-range',
    rating: 4.6,
    reviewCount: 18000,
    imageUrl: 'https://placehold.co/400x400?text=Olay+Regenerist',
    buyUrl: 'https://www.amazon.com/dp/B00006L9LC',
    isActive: true,
    dermatologistApproved: true,
    tags: ['niacinamide', 'anti-aging', 'peptides', 'overnight'],
  },
  {
    name: 'Ultra Facial Cream',
    brand: "Kiehl's",
    category: 'moisturizer',
    description:
      'An iconic lightweight daily moisturiser that provides 24-hour hydration across all weather conditions. Formulated with glacial glycoprotein and imperata cylindrica plant root extract. Non-greasy texture is ideal for daily use under makeup.',
    ingredients: ['Imperata Cylindrica Root Extract', 'Glacial Glycoprotein', 'Glycerin', 'Squalane', 'Betaine'],
    skinTypes: ['all'],
    concerns: ['dryness', 'hydration'],
    price: 36.0,
    priceRange: 'mid-range',
    rating: 4.5,
    reviewCount: 12000,
    imageUrl: 'https://placehold.co/400x400?text=Kiehls+Ultra+Facial',
    buyUrl: 'https://www.kiehls.com',
    isActive: true,
    dermatologistApproved: false,
    tags: ['lightweight', 'hydrating', 'daily'],
  },
  {
    name: 'Tatcha The Water Cream',
    brand: 'Tatcha',
    category: 'moisturizer',
    description:
      'An oil-free, anti-aging water cream that releases a burst of skin-improving Japanese ingredients. Wild rose and leopard lily regulate oil and minimise pores. The lightweight, fast-absorbing formula is ideal for oily and combination skin.',
    ingredients: ['Hadasei-3 Complex', 'Wild Rose', 'Leopard Lily', 'Japanese Laminaria Algae', 'Hyaluronic Acid'],
    skinTypes: ['oily', 'combination'],
    concerns: ['oiliness', 'pores', 'aging', 'brightness'],
    price: 68.0,
    priceRange: 'mid-range',
    rating: 4.6,
    reviewCount: 8000,
    imageUrl: 'https://placehold.co/400x400?text=Tatcha+Water+Cream',
    buyUrl: 'https://www.tatcha.com',
    isActive: true,
    dermatologistApproved: false,
    tags: ['oil-free', 'water-cream', 'Japanese-skincare', 'pore-minimizing'],
  },
  {
    name: 'Protini Polypeptide Cream',
    brand: 'Drunk Elephant',
    category: 'moisturizer',
    description:
      'A protein moisturiser packed with a signal peptide complex, growth factors, and amino acids to support skin firmness and suppleness. The featherlight texture works for all skin types including oily. Free of fragrance and essential oils.',
    ingredients: ['Signal Peptides', 'Growth Factors', 'Amino Acids', 'Pygmy Waterlily', 'Sodium Hyaluronate'],
    skinTypes: ['all'],
    concerns: ['aging', 'fine-lines', 'texture', 'dryness'],
    price: 68.0,
    priceRange: 'mid-range',
    rating: 4.7,
    reviewCount: 9500,
    imageUrl: 'https://placehold.co/400x400?text=Drunk+Elephant+Protini',
    buyUrl: 'https://www.drunkelephant.com',
    isActive: true,
    dermatologistApproved: true,
    tags: ['peptides', 'anti-aging', 'fragrance-free'],
  },
  {
    name: 'Vanicream Moisturizing Skin Cream',
    brand: 'Vanicream',
    category: 'moisturizer',
    description:
      'An ultra-gentle moisturising cream free of dyes, fragrance, masking fragrances, lanolin, parabens, and formaldehyde releasers. Provides long-lasting hydration for eczema and sensitive skin. Dermatologist-tested and hypoallergenic.',
    ingredients: ['Purified Water', 'White Petrolatum', 'Sorbitol Solution', 'Cetearyl Alcohol', 'Propylene Glycol'],
    skinTypes: ['sensitive', 'dry', 'normal'],
    concerns: ['eczema', 'sensitivity', 'dryness', 'redness'],
    price: 14.39,
    priceRange: 'budget',
    rating: 4.8,
    reviewCount: 30000,
    imageUrl: 'https://placehold.co/400x400?text=Vanicream+Moisturizer',
    buyUrl: 'https://www.amazon.com/dp/B000NWGCZ2',
    isActive: true,
    dermatologistApproved: true,
    tags: ['hypoallergenic', 'eczema-safe', 'fragrance-free', 'dye-free'],
  },

  // ── SUNSCREENS ────────────────────────────────────────────────────────────
  {
    name: 'UV Clear Broad-Spectrum SPF 46',
    brand: 'EltaMD',
    category: 'sunscreen',
    description:
      'A lightweight, oil-free sunscreen with zinc oxide that calms sensitive skin types prone to acne, rosacea, and discolouration. Niacinamide (vitamin B3), hyaluronic acid, and lactic acid enhance skin tone and texture. The most recommended sunscreen by dermatologists.',
    ingredients: ['Zinc Oxide 9%', 'Octinoxate 7.5%', 'Niacinamide', 'Hyaluronic Acid', 'Lactic Acid', 'Tocopherol'],
    skinTypes: ['oily', 'combination', 'sensitive', 'normal'],
    concerns: ['acne', 'rosacea', 'sun-protection', 'sensitivity'],
    price: 41.0,
    priceRange: 'mid-range',
    rating: 4.8,
    reviewCount: 22000,
    imageUrl: 'https://placehold.co/400x400?text=EltaMD+UV+Clear',
    buyUrl: 'https://www.amazon.com/dp/B002MSN3QQ',
    isActive: true,
    dermatologistApproved: true,
    tags: ['SPF46', 'mineral', 'oil-free', 'zinc-oxide'],
  },
  {
    name: 'Anthelios Melt-in Milk Sunscreen SPF 60',
    brand: 'La Roche-Posay',
    category: 'sunscreen',
    description:
      'A broad-spectrum SPF 60 sunscreen with the advanced Cell-Ox Shield technology that combines antioxidants with UV filters. The velvety, non-greasy milk texture is water-resistant for 80 minutes. Suitable for sensitive skin.',
    ingredients: ['Avobenzone 3%', 'Homosalate 10%', 'Octisalate 5%', 'Octocrylene 10%', 'Antioxidant Complex'],
    skinTypes: ['sensitive', 'normal', 'dry'],
    concerns: ['sun-protection', 'sensitivity', 'aging'],
    price: 29.99,
    priceRange: 'mid-range',
    rating: 4.7,
    reviewCount: 16000,
    imageUrl: 'https://placehold.co/400x400?text=LRP+Anthelios+SPF60',
    buyUrl: 'https://www.amazon.com/dp/B009BKA54C',
    isActive: true,
    dermatologistApproved: true,
    tags: ['SPF60', 'water-resistant', 'chemical-sunscreen'],
  },
  {
    name: 'Sheer Zinc Dry-Touch SPF 50',
    brand: 'Neutrogena',
    category: 'sunscreen',
    description:
      'A 100% zinc oxide mineral sunscreen with a dry-touch finish that leaves no white cast. Water-resistant for up to 80 minutes and free of synthetic chemical filters. Ideal for those preferring mineral sun protection.',
    ingredients: ['Zinc Oxide 21.6%', 'Glycerin', 'Dimethicone', 'Caprylyl Methicone'],
    skinTypes: ['all', 'sensitive'],
    concerns: ['sun-protection', 'sensitivity'],
    price: 13.97,
    priceRange: 'budget',
    rating: 4.5,
    reviewCount: 20000,
    imageUrl: 'https://placehold.co/400x400?text=Neutrogena+Sheer+Zinc',
    buyUrl: 'https://www.amazon.com/dp/B00HNSSYH0',
    isActive: true,
    dermatologistApproved: true,
    tags: ['SPF50', 'mineral', 'zinc-oxide', 'dry-touch'],
  },
  {
    name: 'Invisible Daily Defense SPF 60+',
    brand: 'Aveeno',
    category: 'sunscreen',
    description:
      'A moisturising sunscreen with oat extract that provides SPF 60+ protection with a non-greasy, invisible finish. Formulated with prebiotic oat that helps maintain skin\'s natural microbiome. Suitable for everyday use on all skin tones.',
    ingredients: ['Avobenzone 3%', 'Homosalate 10%', 'Oat Extract', 'Glycerin', 'Prebiotic Oat'],
    skinTypes: ['all'],
    concerns: ['sun-protection', 'hydration', 'sensitivity'],
    price: 17.49,
    priceRange: 'budget',
    rating: 4.5,
    reviewCount: 10000,
    imageUrl: 'https://placehold.co/400x400?text=Aveeno+SPF60',
    buyUrl: 'https://www.amazon.com/dp/B08L5HQBGJ',
    isActive: true,
    dermatologistApproved: true,
    tags: ['SPF60', 'oat', 'daily', 'invisible-finish'],
  },

  // ── TREATMENTS ────────────────────────────────────────────────────────────
  {
    name: 'Adapalene Gel 0.1%',
    brand: 'Differin',
    category: 'treatment',
    description:
      'The first over-the-counter retinoid approved by the FDA for acne treatment. Adapalene works deep in the pore to clear and prevent acne while improving skin texture and tone. Results typically visible in 8–12 weeks of consistent use.',
    ingredients: ['Adapalene 0.1%', 'Carbomer', 'Edetate Disodium', 'Methylparaben', 'Poloxamer 182'],
    skinTypes: ['oily', 'combination', 'normal'],
    concerns: ['acne', 'blackheads', 'pores', 'texture'],
    price: 31.99,
    priceRange: 'mid-range',
    rating: 4.6,
    reviewCount: 35000,
    imageUrl: 'https://placehold.co/400x400?text=Differin+Adapalene',
    buyUrl: 'https://www.amazon.com/dp/B07L1PHSY9',
    isActive: true,
    dermatologistApproved: true,
    tags: ['retinoid', 'adapalene', 'acne-treatment', 'FDA-approved'],
  },
  {
    name: 'Azelaic Acid Suspension 10%',
    brand: 'The Ordinary',
    category: 'treatment',
    description:
      'A brightening formula with 10% azelaic acid that targets uneven skin tone, blemishes, and redness. Gentle enough for sensitive skin and safe for use during pregnancy. Can be layered under moisturiser morning and evening.',
    ingredients: ['Azelaic Acid 10%', 'Dimethicone', 'Isodecyl Neopentanoate', 'Trisodium Ethylenediamine Disuccinate'],
    skinTypes: ['all', 'sensitive'],
    concerns: ['rosacea', 'acne', 'brightness', 'hyperpigmentation', 'redness'],
    price: 9.9,
    priceRange: 'budget',
    rating: 4.4,
    reviewCount: 15000,
    imageUrl: 'https://placehold.co/400x400?text=TO+Azelaic+Acid',
    buyUrl: 'https://theordinary.com',
    isActive: true,
    dermatologistApproved: false,
    tags: ['azelaic-acid', 'brightening', 'rosacea-safe'],
  },
  {
    name: 'Benzoyl Peroxide Acne Spot Treatment',
    brand: 'Neutrogena',
    category: 'treatment',
    description:
      'A maximum-strength 2.5% benzoyl peroxide spot treatment that starts working on contact to eliminate acne-causing bacteria. The vanishing formula is invisible on skin and non-irritating when used as directed. Clears most blemishes in 2–3 days.',
    ingredients: ['Benzoyl Peroxide 2.5%', 'Carbomer', 'Disodium EDTA', 'Glycerin', 'Sodium Hydroxide'],
    skinTypes: ['oily', 'combination', 'normal'],
    concerns: ['acne', 'blackheads'],
    price: 8.97,
    priceRange: 'budget',
    rating: 4.4,
    reviewCount: 28000,
    imageUrl: 'https://placehold.co/400x400?text=Neutrogena+BPO+Spot',
    buyUrl: 'https://www.amazon.com/dp/B00012NKJG',
    isActive: true,
    dermatologistApproved: true,
    tags: ['benzoyl-peroxide', 'spot-treatment', 'acne'],
  },
  {
    name: 'Alpha Arbutin 2% + HA',
    brand: 'The Ordinary',
    category: 'treatment',
    description:
      'A brightening serum featuring 2% alpha arbutin in a hyaluronic acid base. Alpha arbutin is clinically shown to reduce the appearance of dark spots more effectively than kojic acid. Suitable for all skin types.',
    ingredients: ['Alpha-Arbutin 2%', 'Hyaluronic Acid', 'Glycerin', 'Pentylene Glycol'],
    skinTypes: ['all'],
    concerns: ['hyperpigmentation', 'brightness', 'dark-circles', 'melasma'],
    price: 8.9,
    priceRange: 'budget',
    rating: 4.5,
    reviewCount: 22000,
    imageUrl: 'https://placehold.co/400x400?text=TO+Alpha+Arbutin',
    buyUrl: 'https://theordinary.com',
    isActive: true,
    dermatologistApproved: false,
    tags: ['alpha-arbutin', 'brightening', 'dark-spots'],
  },
  {
    name: 'Pore & Shine Minimizer',
    brand: "Paula's Choice",
    category: 'treatment',
    description:
      'A lightweight lotion with niacinamide and retinol that visibly minimises the appearance of pores and refines skin texture. The silicone-free formula smooths skin without clogging pores. Safe for daily use.',
    ingredients: ['Niacinamide 10%', 'Retinol', 'Hyaluronic Acid', 'Green Tea Extract', 'Ceramide NP'],
    skinTypes: ['oily', 'combination', 'normal'],
    concerns: ['pores', 'oiliness', 'texture', 'acne'],
    price: 34.0,
    priceRange: 'mid-range',
    rating: 4.6,
    reviewCount: 9000,
    imageUrl: 'https://placehold.co/400x400?text=Paulas+Pore+Minimizer',
    buyUrl: 'https://www.paulaschoice.com',
    isActive: true,
    dermatologistApproved: true,
    tags: ['pore-minimizing', 'niacinamide', 'retinol'],
  },

  // ── MASKS ─────────────────────────────────────────────────────────────────
  {
    name: 'Aztec Secret Indian Healing Clay',
    brand: 'Aztec Secret',
    category: 'mask',
    description:
      'The world\'s most powerful facial. 100% natural calcium bentonite clay pulls impurities and excess oil from deep within pores. Mix with apple cider vinegar or water for a deep-pore cleansing treatment. Use weekly for best results.',
    ingredients: ['Calcium Bentonite Clay'],
    skinTypes: ['oily', 'combination'],
    concerns: ['acne', 'pores', 'blackheads', 'oiliness'],
    price: 13.95,
    priceRange: 'budget',
    rating: 4.5,
    reviewCount: 60000,
    imageUrl: 'https://placehold.co/400x400?text=Aztec+Clay+Mask',
    buyUrl: 'https://www.amazon.com/dp/B0014P8L9W',
    isActive: true,
    dermatologistApproved: false,
    tags: ['clay-mask', 'pore-cleansing', 'natural'],
  },
  {
    name: 'Origins Clear Improvement Charcoal Mask',
    brand: 'Origins',
    category: 'mask',
    description:
      'An active charcoal mask that draws out environmental pollutants, dirt, and excess oil. White China clay absorbs impurities while lecithin dissolves dead skin cells. Skin is left visibly clearer, smoother, and pore-refined.',
    ingredients: ['Activated Charcoal', 'White China Clay', 'Lecithin', 'Seaweed Extract'],
    skinTypes: ['oily', 'combination', 'normal'],
    concerns: ['acne', 'pores', 'blackheads', 'texture'],
    price: 32.0,
    priceRange: 'mid-range',
    rating: 4.4,
    reviewCount: 7000,
    imageUrl: 'https://placehold.co/400x400?text=Origins+Charcoal+Mask',
    buyUrl: 'https://www.origins.com',
    isActive: true,
    dermatologistApproved: false,
    tags: ['charcoal-mask', 'pore-cleansing', 'detox'],
  },
  {
    name: 'Glow Recipe Watermelon Glow Sleeping Mask',
    brand: 'Glow Recipe',
    category: 'mask',
    description:
      'An overnight sleeping mask with AHAs from watermelon extract and hyaluronic acid that exfoliates and deeply hydrates while you sleep. Wakes up dull skin for a glowy, bouncy complexion. Suitable for all skin types.',
    ingredients: ['Watermelon Extract', 'Hyaluronic Acid', 'AHA Complex', 'Amino Acids'],
    skinTypes: ['all'],
    concerns: ['brightness', 'dryness', 'texture', 'hydration'],
    price: 45.0,
    priceRange: 'mid-range',
    rating: 4.5,
    reviewCount: 8500,
    imageUrl: 'https://placehold.co/400x400?text=Glow+Recipe+Watermelon',
    buyUrl: 'https://www.glowrecipe.com',
    isActive: true,
    dermatologistApproved: false,
    tags: ['sleeping-mask', 'brightening', 'AHA', 'hydrating'],
  },
  {
    name: 'Sunday Riley Saturn Sulfur Spot Treatment Mask',
    brand: 'Sunday Riley',
    category: 'mask',
    description:
      'A dual-purpose sulfur spot treatment and full-face mask for acne-prone skin. Sulfur and zinc draw out impurities while smoothing skin surface. Niacinamide and black cumin seed oil calm redness and rebalance skin.',
    ingredients: ['Sulfur 10%', 'Zinc', 'Niacinamide', 'Black Cumin Seed Oil', 'Bentonite Clay'],
    skinTypes: ['oily', 'combination'],
    concerns: ['acne', 'pores', 'redness', 'blackheads'],
    price: 55.0,
    priceRange: 'mid-range',
    rating: 4.5,
    reviewCount: 4500,
    imageUrl: 'https://placehold.co/400x400?text=Sunday+Riley+Saturn',
    buyUrl: 'https://www.sundayriley.com',
    isActive: true,
    dermatologistApproved: false,
    tags: ['sulfur', 'acne-mask', 'spot-treatment'],
  },
  {
    name: 'Tatcha The Dewy Skin Mask',
    brand: 'Tatcha',
    category: 'mask',
    description:
      'A plumping wash-off mask with Japanese purple rice, hyaluronic acid, and botanicals that delivers an intense dose of hydration. Skin appears dewier, firmer, and more luminous after a single use. Perfect for dry and dull skin.',
    ingredients: ['Japanese Purple Rice', 'Hadasei-3', 'Hyaluronic Acid', 'Botanical Blend', 'Glycerin'],
    skinTypes: ['dry', 'normal', 'sensitive'],
    concerns: ['dryness', 'hydration', 'brightness', 'aging'],
    price: 68.0,
    priceRange: 'mid-range',
    rating: 4.6,
    reviewCount: 5000,
    imageUrl: 'https://placehold.co/400x400?text=Tatcha+Dewy+Mask',
    buyUrl: 'https://www.tatcha.com',
    isActive: true,
    dermatologistApproved: false,
    tags: ['hydrating-mask', 'plumping', 'Japanese-skincare'],
  },

  // ── EYE CREAMS ────────────────────────────────────────────────────────────
  {
    name: 'Creamy Eye Treatment with Avocado',
    brand: "Kiehl's",
    category: 'eye-cream',
    description:
      'A rich, long-lasting moisturising eye treatment with avocado oil that nourishes and hydrates the delicate eye area. Shea butter and beta-carotene provide intense moisture and antioxidant protection. Reduces the appearance of fine lines and dryness.',
    ingredients: ['Avocado Oil', 'Shea Butter', 'Beta-Carotene', 'Glycerin', 'Beeswax'],
    skinTypes: ['dry', 'normal', 'sensitive'],
    concerns: ['dark-circles', 'fine-lines', 'dryness', 'aging'],
    price: 55.0,
    priceRange: 'mid-range',
    rating: 4.5,
    reviewCount: 6000,
    imageUrl: 'https://placehold.co/400x400?text=Kiehls+Eye+Cream',
    buyUrl: 'https://www.kiehls.com',
    isActive: true,
    dermatologistApproved: false,
    tags: ['eye-cream', 'avocado', 'hydrating'],
  },
  {
    name: 'Retinol Eye Serum',
    brand: "Paula's Choice",
    category: 'eye-cream',
    description:
      'A concentrated retinol eye treatment that reduces the look of wrinkles, crow\'s feet, and under-eye puffiness. The antioxidant-rich formula contains peptides and hyaluronic acid to support retinol efficacy. Ophthalmologist-tested and fragrance-free.',
    ingredients: ['Retinol 0.1%', 'Peptide Complex', 'Hyaluronic Acid', 'Antioxidant Blend', 'Niacinamide'],
    skinTypes: ['normal', 'combination', 'dry'],
    concerns: ['aging', 'fine-lines', 'wrinkles', 'dark-circles'],
    price: 49.0,
    priceRange: 'mid-range',
    rating: 4.5,
    reviewCount: 4200,
    imageUrl: 'https://placehold.co/400x400?text=Paulas+Retinol+Eye',
    buyUrl: 'https://www.paulaschoice.com',
    isActive: true,
    dermatologistApproved: true,
    tags: ['retinol', 'eye-serum', 'anti-aging'],
  },
  {
    name: 'Brightening Eye Gel',
    brand: 'TruSkin',
    category: 'eye-cream',
    description:
      'A lightweight eye gel with vitamin C, hyaluronic acid, and green tea that brightens dark circles and depuffs the under-eye area. The cooling gel texture reduces morning puffiness on contact. Fragrance-free and suitable for all skin types.',
    ingredients: ['Vitamin C', 'Hyaluronic Acid', 'Green Tea Extract', 'Caffeine', 'Aloe Vera'],
    skinTypes: ['all'],
    concerns: ['dark-circles', 'aging', 'brightness'],
    price: 19.99,
    priceRange: 'budget',
    rating: 4.3,
    reviewCount: 8000,
    imageUrl: 'https://placehold.co/400x400?text=TruSkin+Eye+Gel',
    buyUrl: 'https://www.amazon.com/dp/B074KZT9KB',
    isActive: true,
    dermatologistApproved: false,
    tags: ['eye-gel', 'caffeine', 'brightening', 'depuffing'],
  },

  // ── LIP CARE ──────────────────────────────────────────────────────────────
  {
    name: 'Laneige Lip Sleeping Mask',
    brand: 'Laneige',
    category: 'lip-care',
    description:
      'An overnight lip mask that intensively hydrates and restores dry, chapped lips while you sleep. The Berry Mix Complex of vitamin C-rich berries along with hyaluronic acid softens and plumps lips. Wake up to visibly smoother, softer lips.',
    ingredients: ['Hyaluronic Acid', 'Berry Mix Complex', 'Vitamin C', 'Shea Butter', 'Murumuru Seed Butter'],
    skinTypes: ['all'],
    concerns: ['dryness'],
    price: 24.0,
    priceRange: 'mid-range',
    rating: 4.8,
    reviewCount: 40000,
    imageUrl: 'https://placehold.co/400x400?text=Laneige+Lip+Mask',
    buyUrl: 'https://www.amazon.com/dp/B008O9IXEW',
    isActive: true,
    dermatologistApproved: false,
    tags: ['lip-mask', 'overnight', 'hydrating'],
  },
  {
    name: 'Aquaphor Healing Ointment',
    brand: 'Eucerin',
    category: 'lip-care',
    description:
      'A dermatologist-recommended healing ointment that soothes and relieves severely dry, cracked lips. The occlusive formula creates a protective barrier that locks in moisture. Fragrance-free and safe for sensitive skin.',
    ingredients: ['Petrolatum', 'Mineral Oil', 'Ceresin', 'Lanolin Alcohol', 'Glycerin'],
    skinTypes: ['all', 'sensitive'],
    concerns: ['dryness', 'sensitivity'],
    price: 10.49,
    priceRange: 'budget',
    rating: 4.8,
    reviewCount: 55000,
    imageUrl: 'https://placehold.co/400x400?text=Aquaphor+Ointment',
    buyUrl: 'https://www.amazon.com/dp/B0107QP1VE',
    isActive: true,
    dermatologistApproved: true,
    tags: ['healing-ointment', 'occlusive', 'dry-skin'],
  },

  // ── BODY CARE ─────────────────────────────────────────────────────────────
  {
    name: 'Daily Moisturizing Lotion',
    brand: 'Aveeno',
    category: 'body-care',
    description:
      'A clinically proven daily body moisturiser with oat extract that relieves dryness and keeps skin moisturised for 24 hours. The fast-absorbing, non-greasy formula is fragrance-free and safe for sensitive skin. Steroid-free and gentle enough for daily use.',
    ingredients: ['Colloidal Oatmeal 1%', 'Glycerin', 'Dimethicone', 'Cetearyl Alcohol', 'Benzyl Alcohol'],
    skinTypes: ['sensitive', 'dry', 'normal'],
    concerns: ['dryness', 'eczema', 'sensitivity'],
    price: 10.97,
    priceRange: 'budget',
    rating: 4.7,
    reviewCount: 48000,
    imageUrl: 'https://placehold.co/400x400?text=Aveeno+Body+Lotion',
    buyUrl: 'https://www.amazon.com/dp/B00GZPJGB0',
    isActive: true,
    dermatologistApproved: true,
    tags: ['body-lotion', 'oat', 'fragrance-free', 'eczema-safe'],
  },
  {
    name: 'Gold Bond Rough & Bumpy Skin Lotion',
    brand: 'Gold Bond',
    category: 'body-care',
    description:
      'A targeted body lotion with AHAs and BHAs that visibly improves rough, bumpy skin (keratosis pilaris) in 4 weeks. Aloe and 5 intensive moisturisers soften and smooth skin. Fragrance-free and gentle for daily use.',
    ingredients: ['AHA Complex', 'Salicylic Acid 0.5%', 'Aloe Vera', 'Dimethicone', 'Glycerin'],
    skinTypes: ['all'],
    concerns: ['texture', 'dryness', 'sensitivity'],
    price: 12.99,
    priceRange: 'budget',
    rating: 4.5,
    reviewCount: 15000,
    imageUrl: 'https://placehold.co/400x400?text=Gold+Bond+Rough+Bumpy',
    buyUrl: 'https://www.amazon.com/dp/B00IWXQ2FE',
    isActive: true,
    dermatologistApproved: false,
    tags: ['body-lotion', 'AHA', 'keratosis-pilaris', 'rough-skin'],
  },

  // ── ADDITIONAL PRODUCTS (filling to 50) ───────────────────────────────────
  {
    name: 'Antioxidant Pycnogenol C-Magnolia Cream',
    brand: 'SkinCeuticals',
    category: 'moisturizer',
    description:
      'An antioxidant day cream that neutralises free radicals and provides lasting hydration. The formula combines pycnogenol and magnolia extract to visibly reduce redness and strengthen the skin barrier. Ideal for sensitive and reactive skin.',
    ingredients: ['Pycnogenol', 'Magnolia Extract', 'Olive Glycerides', 'Glycerin', 'Squalane'],
    skinTypes: ['sensitive', 'dry', 'normal'],
    concerns: ['redness', 'sensitivity', 'aging', 'dryness'],
    price: 112.0,
    priceRange: 'luxury',
    rating: 4.6,
    reviewCount: 3000,
    imageUrl: 'https://placehold.co/400x400?text=SkinCeuticals+Antioxidant',
    buyUrl: 'https://www.skinceuticals.com',
    isActive: true,
    dermatologistApproved: true,
    tags: ['antioxidant', 'luxury', 'sensitive-skin'],
  },
  {
    name: 'Multi-Correxion 5-in-1 Anti-Aging Serum',
    brand: 'RoC',
    category: 'serum',
    description:
      'A powerful anti-aging serum that addresses five signs of aging: fine lines, wrinkles, texture, dullness, and pores. Proven retinol technology combined with a mineral complex visibly transforms skin in 12 weeks. Fragrance-free and non-comedogenic.',
    ingredients: ['Retinol', 'Mineral Complex', 'Glycerin', 'Niacinamide', 'Adenosine'],
    skinTypes: ['normal', 'combination', 'dry'],
    concerns: ['aging', 'fine-lines', 'wrinkles', 'texture', 'pores'],
    price: 29.97,
    priceRange: 'mid-range',
    rating: 4.4,
    reviewCount: 10000,
    imageUrl: 'https://placehold.co/400x400?text=RoC+Retinol+Serum',
    buyUrl: 'https://www.amazon.com/dp/B07YPXX8KQ',
    isActive: true,
    dermatologistApproved: true,
    tags: ['retinol', 'anti-aging', 'multi-correcting'],
  },
  {
    name: 'Good Genes All-in-One Lactic Acid Treatment',
    brand: 'Sunday Riley',
    category: 'treatment',
    description:
      'A potent lactic acid serum that immediately exfoliates dead skin to reveal brighter, smoother skin. Licorice and lemongrass tackle hyperpigmentation and dullness. One of the most praised brightening treatments in prestige skincare.',
    ingredients: ['Lactic Acid', 'Licorice Root Extract', 'Lemongrass', 'Arbutin', 'Prickly Pear Extract'],
    skinTypes: ['all'],
    concerns: ['brightness', 'hyperpigmentation', 'texture', 'aging'],
    price: 85.0,
    priceRange: 'luxury',
    rating: 4.6,
    reviewCount: 7500,
    imageUrl: 'https://placehold.co/400x400?text=Sunday+Riley+Good+Genes',
    buyUrl: 'https://www.sundayriley.com',
    isActive: true,
    dermatologistApproved: false,
    tags: ['lactic-acid', 'brightening', 'exfoliant', 'luxury'],
  },
  {
    name: 'Ceramidin Cream',
    brand: 'Dr. Jart+',
    category: 'moisturizer',
    description:
      'An intensive multi-ceramide barrier cream that locks in moisture and strengthens the skin barrier. Five types of ceramide create a powerful multi-ceramide complex that fights dryness and dehydration. Safe for sensitive and eczema-prone skin.',
    ingredients: ['Ceramide NP', 'Ceramide AP', 'Ceramide EOP', 'Ceramide NG', 'Ceramide NS', 'Hyaluronic Acid'],
    skinTypes: ['dry', 'sensitive', 'normal'],
    concerns: ['dryness', 'eczema', 'sensitivity', 'hydration'],
    price: 48.0,
    priceRange: 'mid-range',
    rating: 4.7,
    reviewCount: 9000,
    imageUrl: 'https://placehold.co/400x400?text=Dr.Jart+Ceramidin',
    buyUrl: 'https://www.sephora.com/brand/dr-jart-plus',
    isActive: true,
    dermatologistApproved: true,
    tags: ['ceramides', 'barrier-repair', 'eczema-safe'],
  },
  {
    name: 'Youth Surge SPF 15 Age Decelerating Moisturizer',
    brand: "Clinique",
    category: 'moisturizer',
    description:
      'A daily moisturiser with SPF 15 that combines anti-aging Sirtuin technology with broad-spectrum sun protection. The lightweight formula adapts to oily, combination, and dry skin variants. Clinique-tested for allergy and ophthalmologist-tested.',
    ingredients: ['SPF 15', 'SNAP-8 Peptide', 'Resveratrol', 'Salicylic Acid', 'Glycerin'],
    skinTypes: ['all'],
    concerns: ['aging', 'sun-protection', 'fine-lines'],
    price: 52.5,
    priceRange: 'mid-range',
    rating: 4.4,
    reviewCount: 6500,
    imageUrl: 'https://placehold.co/400x400?text=Clinique+Youth+Surge',
    buyUrl: 'https://www.clinique.com',
    isActive: true,
    dermatologistApproved: true,
    tags: ['SPF15', 'anti-aging', 'daily-moisturizer'],
  },
  {
    name: 'Overnight Repair Serum',
    brand: 'Neutrogena',
    category: 'serum',
    description:
      'A retinol-powered overnight serum that visibly reduces fine lines, uneven skin tone, and roughness in 4 weeks. The Accelerated Retinol SA formula combines retinol with hyaluronic acid and glucose complex for effective yet gentle results.',
    ingredients: ['Retinol', 'Hyaluronic Acid', 'Glucose Complex', 'Glycerin', 'Dimethicone'],
    skinTypes: ['normal', 'combination', 'dry'],
    concerns: ['aging', 'fine-lines', 'texture', 'brightness'],
    price: 22.99,
    priceRange: 'budget',
    rating: 4.4,
    reviewCount: 14000,
    imageUrl: 'https://placehold.co/400x400?text=Neutrogena+Retinol+Serum',
    buyUrl: 'https://www.amazon.com/dp/B07BQKYFZ9',
    isActive: true,
    dermatologistApproved: true,
    tags: ['retinol', 'overnight', 'anti-aging', 'budget'],
  },
  {
    name: 'Phyto Corrective Gel',
    brand: 'SkinCeuticals',
    category: 'serum',
    description:
      'A calming botanical gel serum featuring botanical extracts and hyaluronic acid that soothes sensitised, redness-prone skin. The oil-free formula provides immediate visible redness relief while improving skin clarity over time.',
    ingredients: ['Cucumber Extract', 'Thyme Extract', 'Hyaluronic Acid', 'Dipeptide-2', 'Dipotassium Glycyrrhizate'],
    skinTypes: ['sensitive', 'oily', 'normal'],
    concerns: ['redness', 'sensitivity', 'rosacea', 'brightness'],
    price: 102.0,
    priceRange: 'luxury',
    rating: 4.5,
    reviewCount: 2800,
    imageUrl: 'https://placehold.co/400x400?text=SkinCeuticals+Phyto',
    buyUrl: 'https://www.skinceuticals.com',
    isActive: true,
    dermatologistApproved: true,
    tags: ['calming', 'redness-relief', 'luxury', 'rosacea'],
  },
  {
    name: 'Vitamin C Brightening Essence Toner',
    brand: 'Murad',
    category: 'toner',
    description:
      'A brightening essence-toner hybrid with ethyl ascorbic acid (vitamin C) that delivers antioxidant protection while refining pores and evening skin tone. Glycolic acid gently resurfaces while hyaluronic acid maintains hydration levels.',
    ingredients: ['Ethyl Ascorbic Acid', 'Glycolic Acid', 'Hyaluronic Acid', 'Niacinamide', 'Kakadu Plum Extract'],
    skinTypes: ['normal', 'combination', 'oily'],
    concerns: ['brightness', 'hyperpigmentation', 'pores', 'texture'],
    price: 45.0,
    priceRange: 'mid-range',
    rating: 4.4,
    reviewCount: 3500,
    imageUrl: 'https://placehold.co/400x400?text=Murad+Vitamin+C+Toner',
    buyUrl: 'https://www.murad.com',
    isActive: true,
    dermatologistApproved: false,
    tags: ['vitamin-C', 'brightening', 'essence-toner'],
  },
  {
    name: 'CeraVe SA Cleanser',
    brand: 'CeraVe',
    category: 'cleanser',
    description:
      'A salicylic acid cleanser that smooths and softens rough, bumpy skin while maintaining the protective skin barrier. The combination of salicylic acid, niacinamide, and ceramides gently exfoliates and nourishes simultaneously. For rough and bumpy skin types.',
    ingredients: ['Salicylic Acid 0.5%', 'Ceramide NP', 'Ceramide AP', 'Ceramide EOP', 'Niacinamide', 'Hyaluronic Acid'],
    skinTypes: ['oily', 'combination', 'normal'],
    concerns: ['acne', 'texture', 'pores', 'blackheads'],
    price: 12.49,
    priceRange: 'budget',
    rating: 4.6,
    reviewCount: 19000,
    imageUrl: 'https://placehold.co/400x400?text=CeraVe+SA+Cleanser',
    buyUrl: 'https://www.amazon.com/dp/B07C8TVMZV',
    isActive: true,
    dermatologistApproved: true,
    tags: ['salicylic-acid', 'exfoliating', 'acne-cleanser'],
  },
  {
    name: 'Toleriane Double Repair Moisturizer',
    brand: 'La Roche-Posay',
    category: 'moisturizer',
    description:
      'A clinically proven prebiotic moisturiser that restores the skin barrier in just one hour. The formula combines ceramides, niacinamide, and glycerin with La Roche-Posay Thermal Spring Water to rehydrate and soothe sensitive skin.',
    ingredients: ['Ceramide NP', 'Niacinamide', 'Glycerin', 'La Roche-Posay Thermal Spring Water', 'Prebiotic Thermal Water'],
    skinTypes: ['sensitive', 'dry', 'normal'],
    concerns: ['dryness', 'sensitivity', 'redness', 'hydration'],
    price: 22.99,
    priceRange: 'budget',
    rating: 4.7,
    reviewCount: 17000,
    imageUrl: 'https://placehold.co/400x400?text=LRP+Double+Repair',
    buyUrl: 'https://www.amazon.com/dp/B01MQXLBLO',
    isActive: true,
    dermatologistApproved: true,
    tags: ['prebiotic', 'ceramides', 'barrier-repair', 'sensitive'],
  },
  {
    name: 'Tatcha The Essence',
    brand: 'Tatcha',
    category: 'toner',
    description:
      'A skin-plumping treatment essence inspired by the traditional skincare rituals of Japanese geishas. Triple-fermented Japanese ingredients work to hydrate and illuminate, acting as a booster for the skincare routine that follows. Suitable for all skin types.',
    ingredients: ['Hadasei-3 (Fermented Rice, Green Tea, Algae)', 'Hyaluronic Acid', 'Glycerin', 'Squalane'],
    skinTypes: ['all'],
    concerns: ['brightness', 'hydration', 'aging', 'texture'],
    price: 105.0,
    priceRange: 'luxury',
    rating: 4.6,
    reviewCount: 4500,
    imageUrl: 'https://placehold.co/400x400?text=Tatcha+Essence',
    buyUrl: 'https://www.tatcha.com',
    isActive: true,
    dermatologistApproved: false,
    tags: ['essence', 'fermented', 'luxury', 'Japanese-skincare'],
  },
  {
    name: 'Umbra Sheer Physical Daily Defense SPF 30',
    brand: 'Drunk Elephant',
    category: 'sunscreen',
    description:
      'A 100% mineral sunscreen with zinc oxide in a silky, featherweight serum that protects while delivering antioxidants and vitamin C. The formula leaves no white cast and layers seamlessly under makeup. Fragrance-free and non-comedogenic.',
    ingredients: ['Zinc Oxide 20%', 'Vitamin C', 'Sunflower Shoot Extract', 'Squalane', 'Glycerin'],
    skinTypes: ['all', 'sensitive'],
    concerns: ['sun-protection', 'brightness', 'sensitivity'],
    price: 36.0,
    priceRange: 'mid-range',
    rating: 4.5,
    reviewCount: 7500,
    imageUrl: 'https://placehold.co/400x400?text=Drunk+Elephant+SPF30',
    buyUrl: 'https://www.drunkelephant.com',
    isActive: true,
    dermatologistApproved: true,
    tags: ['SPF30', 'mineral', 'no-white-cast', 'vitamin-C'],
  },
];

const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/skincheck');
    console.log('Connected to MongoDB');

    await Product.deleteMany({});
    console.log('Cleared existing products');

    const inserted = await Product.insertMany(products);
    console.log(`Successfully seeded ${inserted.length} products`);

    await mongoose.disconnect();
    console.log('Disconnected from MongoDB');
    process.exit(0);
  } catch (err) {
    console.error('Seed error:', err.message);
    process.exit(1);
  }
};

seed();
